NUM_MATH_OPS: 28
STATIC_ADDRS: 22
LEN_IND_ADDR: 3
NUM_DYNAMIC_ADDR_SPACES: 5
NEW_INST_MIN_LEN: 8
NEW_INST_MAX_LEN: 24
NGEN: 10
POPSIZE: 50
TOURSIZE: 4
MU: 25
lambda_ : 50
CXPR: 0.4
MUTPR: 0.4
nproc: 16
NUM_NETS: 500
SUBSAMPLE_NETS: 20
NUM_SAMPLING_EVAL: 4
rangemix: True
MIN_TREE_DEPTH: 2
MAX_TREE_DEPTH: 6
data_folder: "data2"