bash runjob.sh "python verify_scores.py --batch_size 16 " "nb2_cf10"
bash runjob.sh "python verify_scores.py --batch_size 16 --dataset cifar100" "nb2_cf100"
bash runjob.sh "python verify_scores.py --batch_size 16 --dataset ImageNet16-120" "nb2_in"
bash runjob.sh "python verify_scores.py --batch_size 16 --nds_space nds_amoeba --search_space NDS" "amoeba"
bash runjob.sh "python verify_scores.py --batch_size 16 --nds_space nds_darts --search_space NDS" "darts"
bash runjob.sh "python verify_scores.py --batch_size 16 --nds_space nds_pnas --search_space NDS" "pnas"
bash runjob.sh "python verify_scores.py --batch_size 16 --nds_space nds_nasnet --search_space NDS" "nasnet"
bash runjob.sh "python verify_scores.py --batch_size 16 --nds_space nds_enas --search_space NDS" "enas"
bash runjob.sh "python verify_scores.py --batch_size 64 --search_space NATSBench" "nats"

